import { PublicationFragment } from '@/generated/graphql';
import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';

const MetaTags = ({ publication }: { publication: PublicationFragment }) => {
	return (
		<>
			<title>{publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'}</title>
			<meta
				name="description"
				content={
					publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
				}
			/>
			<meta property="twitter:card" content="summary_large_image" />
			<meta
				property="twitter:title"
				content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'}
			/>
			<meta
				property="twitter:description"
				content={
					publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
				}
			/>
			<meta
				property="og:image"
				content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
			/>
			<meta
				property="twitter:image"
				content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
			/>
			<script
				type="application/ld+json"
				dangerouslySetInnerHTML={{
					__html: JSON.stringify(addPublicationJsonLd(publication)),
				}}
			/>
		</>
	);
};
export default MetaTags;
